# Generated by Django 4.1.3 on 2022-12-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufacturing_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
